### ISSUE TITLE
Ww Vv adjustment

### ISSUE THREAD

**Issue by vv-monsalve** [vv-monsalve/Alata#4]
**Render on Windows Chrome before fixes:**
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67223890-b7efe480-f3f5-11e9-93e8-5ce41c753cff.jpg)

**Render after adjustments**
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67223815-92fb7180-f3f5-11e9-8257-c7bfef74339b.jpg)

**Comment by vv-monsalve** [comment]
0 -22 / 735 25
![Desktop_Windows_10_chrome_69 0_Overhangs-AZones](https://user-images.githubusercontent.com/48698976/67240999-36f61480-f418-11e9-999b-0e3fee348ce8.jpg)

**Comment by vv-monsalve** [comment]
Rendering on TTF's from today's copy source

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67702368-a1123a80-f97f-11e9-896f-692ab2dbf47b.jpg)

**Comment by vv-monsalve** [comment]
Render en copy 2

![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67704435-1f241080-f983-11e9-9c3e-74b6392f427d.jpg)

**Comment by m4rc1e** [comment]
- Numerals don't align
- Overshoots may be pushed too far. Look at 21pt, the "A" greatly extends past the cap height.

What do the fonts look like unhinted?

**Comment by vv-monsalve** [comment]
Overshoots and overhangs back to lower values, no hinted font, renders:
### Windows 10 Chrome 69
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/48698976/67797828-83f96c80-fa50-11e9-8ab9-c00436edb5ca.jpg)
### OS X High Sierra Safari 11
![Desktop_OS_X_High_Sierra_safari_11 1_](https://user-images.githubusercontent.com/48698976/67797854-8cea3e00-fa50-11e9-9ffa-7b39d58d54e8.jpg)
### Windows 10 Firefox 62
![Desktop_Windows_10_firefox_62 0_](https://user-images.githubusercontent.com/48698976/67797873-9378b580-fa50-11e9-96d7-cb10b769fbc0.jpg)

**Comment by m4rc1e** [comment]
Vertical metrics are changing between each check. This make it difficult to diff.

**Comment by vv-monsalve** [comment]
I'll go back to PR version and resume fixes from there.

**Comment by vv-monsalve** [comment]
New revisions on [Issue 5](https://github.com/vv-monsalve/Alata/issues/5)
